### ISSUE TITLE
Add versioned dirs for VOLUME

### ISSUE THREAD

**Issue by mfojtik** [openshift/postgresql#2]
We had a short discussion about this with @mnagy today, the problem I can see is that we are going to use the same directory for 'data' for all versions of postgresql/mongo/mysql.

What happen when we will have multiple versions of these where all databases will write into same directory. Where this is not a problem if you don't want to use your existing volume, it might be problem if you do. In that case, your database might be corrupted by the new version...

I propose to use something like:

```
VOLUME /var/lib/pgsql-92/data
VOLUME /var/lib/pgsql-95/data
etc...
```

Alternatively, we can store the version of postgresql in VOLUME and check if the version matches with the current version:

```
echo $POSTGRESQL_VERSION > /var/lib/pgsql/data/.version
 ```

**Comment by mfojtik** [comment]
@bparees @jhadvig @soltysh PTAL

**Comment by mnagy** [comment]
Wouldn't it be an error to run two postgres versions with the same volume?

**Comment by soltysh** [comment]
I'd say this should be transparent to user, thus I back the second solution with `.version` file.

**Comment by bparees** [comment]
I'm still inclined towards the view that we do nothing special here.  If you reuse a volume after changing the image, that's a decision you've made explicitly.

We should add logic to the DB images to check if the volume contains a DB already and if so, check if it needs to migrate the DB version if appropriate and possible.  And if we can determine that the DB volume is unusable because it's incompatible, we should error.  But all of that should be determinable via the DB code itself, we shouldn't need to "mark" the volume with a version.  

After all, someone could also use some other mysql image to create the volume, then use our image, so you can't really make assumptions about what will be on there.

**Comment by hhorak** [comment]
-1 for versioned dirs, I basically agree with @bparees

**Comment by rhcarvalho** [comment]
-1 for this as well.

When we use a persistent volume, we mount it to `/var/lib/pgsql/data`. Changing the mount point, to say `/var/lib/pgsql-92/data`, won't change the data in the volume. This would make the image diverge more from existing conventions without solving the incompatibility problem that was brought up.

As for what we can expect for the present and near future, we're supporting PostgreSQL 9.x (9.2 now, open PR for 9.4), which guarantees no changes in the internal storage format:

http://www.postgresql.org/docs/current/static/upgrading.html
> Minor releases never change the internal storage format and are always compatible with earlier and later minor releases of the same major version number, e.g., 8.4.2 is compatible with 8.4, 8.4.1 and 8.4.6. To update between compatible versions, you simply replace the executables while the server is down and restart the server. The data directory remains unchanged — minor upgrades are that simple.

**Comment by bparees** [comment]
@mfojtik ok to close?

**Comment by mfojtik** [comment]
@bparees so the conclusion is to not have versioned dirs and not have `.version` with information about what version of DB was used to create the data?

**Comment by bparees** [comment]
@mfojtik right...."do nothing, it's the DBs problem and we don't want to introduce arbitrary content into the db data directory"
