### ISSUE TITLE
Instructions to use on OpenShift

### ISSUE THREAD

**Issue by thesteve0** [openshift/postgresql#30]
Why are there no instructions on how to use this image on OpenShift. It does not seem that I can just new-app this docker image.

**Comment by mnagy** [comment]
OS related documentation is here: https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/using_images/db_images/postgresql.html

**Comment by thesteve0** [comment]
1) The documentation on this page states this is Postgresql for OpenShift yet gives no directions how to run it on OpenShift - only as a docker container
2) This image does not run on OpenShift unless you set the environment variables - that is not clear on this page
3) The other doc should not talk about docker exec but instead should give examples with oc exec since this is openshift documentation. We expect our users to be going through OpenShift not docker directly. 
4) New-app is the command we seem to be prefering for web developers to use. We should have documentaiton on this read me that specifically uses your example for new-app you sent me

Thanks
steve

**Comment by rhcarvalho** [comment]
This is an interesting docs request. I've felt the same need for improving the docs here in the past, and one thing that I remember from that time is that there's a sort of implicit template that we try to keep consistent across all image repos (DBs and language builders).

So this seems to be a chance to revisit all images to apply improvements consistently.

However, @thesteve0 your items (1) and (3) need and update, as this image is not only for OpenShift, but also meant to run in other contexts -- that's why documenting how it works with `docker run`.

**Comment by bparees** [comment]
@thesteve0 please take another look at the docs, i think all your concerns are addressed..the docs use oc new-app to explain how to run it, give oc exec examples, and  mention required variables

**Comment by rhcarvalho** [comment]
@bparees at a minimum we could have a link in the README pointing to https://docs.openshift.org/latest/using_images/db_images/postgresql.html (similarly, the same for other images)

**Comment by bparees** [comment]
@rhcarvalho yes we can do that.

**Comment by thesteve0** [comment]
I just checked my email account and found this - I am not sure why github hasn't updated it for all my github stuff. Anyway - seems that images under the openshift/<image> should primarily be for running in openshift. Running as stand alone should not be how the documentation starts. 


OpenShift users should not see the stuff about docker to start - other than that this doc looks awesome! Thanks so much for putting the time in doing this.
