### ISSUE TITLE
Permissions 0777 set on some directories within Dockerfile

### ISSUE THREAD

**Issue by praiskup** [openshift/postgresql#64]
As discussed in openshift/mysql/pull/94 and mysql/pull/92#issuecomment-139270899.

Fwiw "Reorder Dockerfile for better use of cache" commit message did not help me
to understand the reasoning for the `chmod a+rwx ..` change...

**Comment by mfojtik** [comment]
@praiskup the reason is that when you developing the image and you have to rebuild it to pickup changes in the scripts, you don't want to wait for yum to finish installing all RPM's. If you move the COPY instruction below that, docker will use the cache to give you the layer with RPMS and the image rebuild is much faster. However, we need to make the directory world writeable as an extra step (previously we did that in yum install step) but this step runs 100x faster than yum install ;-).

So it is mostly for developers convenience as you don't have wait for yum install to complete. Also we squash the image when we build it in Jenkins, so there is no overheat (or extra layer). Hope this explains it.

**Comment by hhorak** [comment]
I believe we should use the same approach as in mysql -- let `/var/lib/pgsql` be owned by `postgres.0` and use just `chmod g+rwx`.
